// src/components/layout/Footer.vue
<template>
  <footer class="footer">
    <div class="container">
      <div class="row">
        <div class="col">
          <p>TODO © HeimHirschEli</p>
        </div>
        <div class="col text-right">
          <p>Portal TODO - API TODO</p>
        </div>
      </div>
    </div>
  </footer>
</template>

<style lang="scss">
footer.footer {
  font-size: .8em;
  background: transparent;
}
</style>

// src/app/components/layout/Footer.tsx
import * as React from 'react';

import { getAppName, getAppVersion } from '../../utils/app-config';
import './Footer.scss';

/**
 * @name Footer
 * @description Renders the footer for the app.
 */
export const Footer = ({ }) => (
  <footer className="footer">
    <div className="container">
      <div className="row">
        <div className="col">
          <p>{getAppName()} © HeimHirschEli</p>
        </div>
        <div className="col text-right">
          <p>Portal {getAppVersion()} - API {}</p>
        </div>
      </div>
    </div>
  </footer>
);
