// src/components/auth/Login.vue
<template>
  <div class="login">
    <form class="form-signin" noValidate>
      <label htmlFor="inputUsername" class="sr-only">{{ $t('label.username') }}</label>
      <input
        id="inputUsername"
        class="form-control"
        type="text"
        v-bind:placeholder="$t('label.username')"
        v-model="username"
        required />

      <label htmlFor="inputPassword" class="sr-only">{{ $t('label.password') }}</label>
      <input
        id="inputPassword"
        class="form-control"
        type="password"
        v-bind:placeholder="$t('label.password')"
        v-model="password"
        required />

      <button
        class="btn btn-lg btn-primary btn-block"
        v-on:click="signIn()">
        {{ $t("login.sign_in" )}}
      </button>
    </form>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import Component from 'vue-class-component';
import { Action, Getter, State } from 'vuex-class';
import { AuthState, Credentials } from '../../states/modules/auth';

@Component
export default class Login extends Vue {
  public username = '';
  public password = '';

  @State('auth')
  public authState: any;

  @Getter('auth/isAuthenticated')
  public isAuthenticated: boolean;

  @Action(`auth/signInUser`)
  public signInUser: (cred: Credentials) => void;

  private log = this.$createLogger(this);

  public created(): void {
    this.log.info('created', this.authState);
    this.log.info('signInUser', this.signInUser);
  }

  public signIn(): void {
    this.signInUser({
      username: this.username,
      password: this.password,
    });
  }

}
</script>

<style lang="scss">
.form-signin {
  width: 100%;
  margin: 0 auto;
}

.form-signin .checkbox {
  font-weight: 400;
}

.form-signin .form-control {
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
  font-size: 16px;
}

.form-signin .form-control:focus {
  z-index: 2;
}

.form-signin input[type="text"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}

.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
</style>

// src/app/components/auth/Login.tsx
import * as React from "react";
import { I18n } from "react-i18next";

import "./Login.scss";

interface Props { }

interface State { }

export default class Login extends React.Component<Props, State> {

  public render(): React.ReactNode {
    return (
      <I18n>
        {
          (t) => (
            <div className="login">
              <form className="form-signin">
                <label htmlFor="inputUsername" className="sr-only">{t("LABEL.USERNAME")}</label>
                <input type="text" id="inputUsername" className="form-control" placeholder={t("LABEL.USERNAME")} required />

                <label htmlFor="inputPassword" className="sr-only">{t("LABEL.PASSWORD")}</label>
                <input type="password" id="inputPassword" className="form-control" placeholder={t("LABEL.PASSWORD")} required />

                <button className="btn btn-lg btn-primary btn-block" type="submit">
                  {t("LOGIN.SIGN_IN")}
                </button>
              </form>
            </div>
          )
        }
      </I18n>
    );
  }
}
