// src/app/components/App.tsx
import React from "react";
import { Route, Switch } from "react-router-dom";

import { Routes } from "../routes/Routes";
import Footer from "./layout/Footer";
import Header from "./layout/Header";

/**
 * @name App
 * @description Renders our main skeleton of our app;
 */
export const App = ({ }) => (
  <div>
    <Header />
    <Routes />
    <Footer />
  </div>
);

// src/App.vue
<template>
  <div id="app">
    <Header/>
    <main class="container">
      <router-view/>
    </main>
    <Footer/>
  </div>
</template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';

import Header from './components/layout/Header.vue';
import Footer from './components/layout/Footer.vue';

@Component({
  components: {
    Header,
    Footer,
  },
})
export default class Home extends Vue {}
</script>
